name: Lighthouse CI
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g @lhci/cli
      - run: |
          LHCI_BUILD_CONTEXT__CURRENT_HASH=$(node -p "new Date().getTime().toString(16).split('').reverse().join('')")
          echo $LHCI_BUILD_CONTEXT__CURRENT_HASH
          export LHCI_BUILD_CONTEXT__CURRENT_HASH
      - run: lhci collect --url=https://www.esna.cloud --collect.numberOfRuns=2
      - run: lhci upload --target=temporary-public-storage
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
